### ISSUE TITLE
Cannot use the gradle module plugin with Yubikey or other PKCS11 signing.

### ISSUE THREAD

**Issue by pturmel** [inductiveautomation/ignition-module-tools#41]
I would like to migrate to gradle builds (from ant, skipping maven) but the properties for configuring module signing do not support the Module Signer's -pkcs11-cfg option.  Is there any chance this can be added?

**Comment by PerryAJ** [comment]
Hey Phil,

I'm going to have to do some looking before I can commit, but if there's no inherent technical limitation, I'd like to get this done.  I'm a bit time strapped at the moment, but will make it a top priority when I've cleared a bit off the old plate (assuming someone else doesn't notice this and beat me to it).

Appreciate you pointing out the gap in support, will follow up when I can say something more specific.

**Comment by pturmel** [comment]
I may beat you to it, then.  (I supplied the code Kevin committed to add pkcs11 to the module signer.)

**Comment by PerryAJ** [comment]
PRs are always welcome!

I'll try and look at this over the next couple days though if you don't beat me to it.  I haven't seen the the changes you're mentioning about the signer, where can I find those? KevinH?

**Comment by kevinherron** [comment]
This commit: https://github.com/inductiveautomation/module-signer/commit/7a3df1e5f313d07c1b6aa105f92908c41d93899a

**Comment by PerryAJ** [comment]
> This commit: [inductiveautomation/module-signer@7a3df1e](https://github.com/inductiveautomation/module-signer/commit/7a3df1e5f313d07c1b6aa105f92908c41d93899a)

Oh, I'm following now, thx for the tip - I thought Phil was talking about a more recent change.  

With that context, it doesn't seem like we'd need an update to the signer dependency at all (and noticed we have some old/outstanding PRs on that lib that prob should get looked at @kevinherron). We'll need to update the SignModule tasks's implementation.  Looks like it might just be a minor change in the setup/invocation of the signer [around here](https://github.com/inductiveautomation/ignition-module-tools/blob/57a4acb72c9579a71296a7d4c2aae7cbda1206a5/gradle-module-plugin/src/main/kotlin/io/ia/sdk/gradle/modl/task/SignModule.kt#LL250C35-L250C35).  

Will see if I can get a PR up (or find someone with some time and interest) in the next few days.

**Comment by PerryAJ** [comment]
Haven't had time to get to this, but we did open an internal ticket with high priority today to start getting some eyes on this. No timeline/eta, but something that is going to get looked at in the near-term (IGN-7871 is our internal ticket to get this some attention).

**Comment by brianeray** [comment]
@pturmel , I'm going to try to take a look at this before the end of the current month (August). :crossed_fingers:

**Comment by brianeray** [comment]
November is the new August. I'm looking at this now.

**Comment by brianeray** [comment]
Associated PR merged and `io.ia.sdk.modl` Gradle plugin published.
