### ISSUE TITLE
Gradle error on fresh generated module skeleton

### ISSUE THREAD

**Issue by thirdgen88** [inductiveautomation/ignition-module-tools#49]
When using [generator-cli](https://github.com/inductiveautomation/ignition-module-tools/tree/master/generator/generator-cli#readme), a freshly created project produces the following Gradle error when attempting to build:

```
* What went wrong:
Script compilation error:

  Line 90:     moduleDependencySpecs { }
               ^ Unresolved reference: moduleDependencySpecs
```

This appears to be due to the templating in _generator_ still emitting version `0.1.1` for the Ignition Module Plugin (`io.ia.sdk.modl`) instead of the latest `0.3.0` (where `moduleDependencySpecs` was introduced).  In a quick search through the code, it looks like we might need to update a few areas where the previous version number was used; hopefully we can DRY that up in the process.

**Comment by brianeray** [comment]
For internal tracking purposes: IGN-10597.

**Comment by brianeray** [comment]
Local testing with the #54 commit suggests that lining up all the version references from `generator` logic to `gradle-module-plugin`'s version does the trick.

```powershell
.\gradlew.bat --% build

# ...

> Task :signModule SKIPPED
useUnsignedModule specified in Module Settings. Module Signing will be skipped

BUILD SUCCESSFUL in 932ms
8 actionable tasks: 2 executed, 6 up-to-date
```

There are several other patches to fit into this release but once `0.4.0` is ready, I'll close out this issue.

**Comment by brianeray** [comment]
#59 fixes this.
